AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Parameters:
  BucketName:
    Type: String
    Default: thumbnail-bucket-python-oleksii # Define unique name for the input bucket


Resources:

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  ThumbnailsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  ThumbnailsBucketOutput:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketName}-thumbs"

  ThumbnailFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: src/app.s3_thumbnail_generator
      Runtime: python3.9
      CodeUri: .
      Environment:
        Variables:
            THUMBNAIL_SIZE: 128 
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref BucketName
        - S3WritePolicy:
            BucketName: !Sub "${BucketName}-thumbs"

      Events:
        S3NewObjectEvent:
          Type: S3
          Properties:
            Bucket: !Ref ThumbnailsBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: ".png"

  LambdaInvokePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !GetAtt ThumbnailFunction.Arn
      Action: "lambda:InvokeFunction"
      Principal: "s3.amazonaws.com"
      SourceArn: !GetAtt ThumbnailsBucket.Arn

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"
